language: go

go:
  - 1.4.1

install:
  - sudo apt-get install libgtk-3-dev libappindicator3-dev
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  # This unencryptes envvars.bash.enc into envvars.bash so that we can run the tests
  - openssl aes-256-cbc -K $encrypted_9c9444fdc7c6_key -iv $encrypted_9c9444fdc7c6_iv -in envvars.bash.enc -out envvars.bash -d
  - ./testandcover.bash

after_success:
  - GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
