language: go

go:
  - 1.3.3

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - ./testandcover.bash
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci